def generator(f):
    print('generated by generator')

    def generated(*args, **kwargs):
        print('called generated')
        return f("""①""")

    return generated


def generator_lambda(f):
    print('generated by generator_lambda')
    return lambda *args, **kwargs: f("""①""")


def func(a, b):
    return a * b


generated_func = generator(func)
generated_func_lambda = generator_lambda(func)

print(func(2, 3))
print(generated_func(4, 5))
print(generated_func_lambda(6, 7))
# 出力結果
# """②"""
# """③"""
# 6
# """④"""
# 20
# 42
